version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - 5432:5432 
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpw
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/var/lib/mongo/data

volumes:
  pgdata:
  mongodbdata: