version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - 5432:5432 
    volumes:
      - /var/lib/postgresql/data
    
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
  mongodbdata: