import { Metadata } from 'next';
import './globals.css';
import ToastrProvider from './providers/ToastrProvider';
import SignalRProvider from './providers/SignalRProvider';
import { getCurrentUser } from './actions/authActions';
import Header from './header/Header';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by Carsties',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang='en'>
      <body>
        <ToastrProvider />
        <Header />
        <main className='container mx-auto px-5 pt-10'>
          <SignalRProvider user={user}>{children}</SignalRProvider>
        </main>
      </body>
    </html>
  );
}
